//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGTechTest.WebAPI.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IDTestFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDTestFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BGTechTest.WebAPI.Tests.Resources.IDTestFile", typeof(IDTestFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 870904642489,The identity number contains characters that are not numbers|The Identity number has less than 13 digits
        ///870904642489001,The identity number contains characters that are not numbers|The Identity number has more than 13 digits
        ///870904642489,The identity number contains characters that are not numbers|The Identity number has less than 13 digits
        ///870904642489001,The identity number contains characters that are not numbers|The Identity number has more than 13 digits
        ///870904642489,The identity numb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Csv_InValidIdFile {
            get {
                return ResourceManager.GetString("Csv_InValidIdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male
        ///8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male
        ///8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male
        ///8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male
        ///8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male
        ///8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Csv_ValidIdFile {
            get {
                return ResourceManager.GetString("Csv_ValidIdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///8605065397083,1986/05/06,SA Citizen,Male.
        /// </summary>
        internal static string IdErrorInfo {
            get {
                return ResourceManager.GetString("IdErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8709046424188,1987/09/04,Non-SA Citizen,Male
        ///8605065397083,1986/05/06,SA Citizen,Male.
        /// </summary>
        internal static string IdInfo {
            get {
                return ResourceManager.GetString("IdInfo", resourceCulture);
            }
        }
    }
}
